server.port=8081
spring.application.name=prueba_api

# Configuracion de PostgreSQL (Neon DB)
spring.datasource.url=jdbc:postgresql://ep-square-dream-ax1lux4e-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_5EchUnxOC9Te
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# ddl-auto=update: conserva los datos existentes y solo ajusta el esquema si cambian las entidades.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true


# Configuracion Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss
spring.jackson.serialization.write-dates-as-timestamps=false

spring.sql.init.mode=always
spring.sql.init.platform=postgres




